#!/usr/bin/env python3
"""
generate_assets.py — Procedural low-poly OBJ generator for Skypop Collective style
====================================================================================
Generates the following texture-free, flat-normal OBJ meshes:

  meshes/character.obj   — simple low-poly humanoid (~100 faces)
  meshes/tree_a.obj      — chunky conical foliage tree
  meshes/tree_b.obj      — tiered / layered foliage tree
  meshes/tree_c.obj      — round bushy tree
  meshes/ground.obj      — flat tiled ground island

All meshes use per-face normals (no 'vn' or smooth groups), so the NPR
integrator receives flat geometric_normals from Embree for cel-shading.

Run from the scene directory:
    cd scenes/skypop_game && python3 generate_assets.py
"""

import math
import os

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "meshes")
os.makedirs(OUT_DIR, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# OBJ writing helpers
# ─────────────────────────────────────────────────────────────────────────────

class ObjBuilder:
    """Accumulates vertices and faces, then writes a flat-normal OBJ."""

    def __init__(self):
        self.verts = []   # list of (x, y, z)
        self.faces = []   # list of tuples of 1-based vert indices

    def v(self, x, y, z):
        self.verts.append((x, y, z))
        return len(self.verts)   # 1-based index

    def f(self, *indices):
        """Add a face.  Indices are 1-based."""
        self.faces.append(tuple(indices))

    def add_quad(self, a, b, c, d):
        """Two-triangle quad from four 1-based vert indices."""
        self.f(a, b, c)
        self.f(a, c, d)

    def write(self, path):
        with open(path, 'w') as fp:
            fp.write(f"# Generated by generate_assets.py — {len(self.verts)} verts, "
                     f"{len(self.faces)} faces\n")
            fp.write("# No vertex normals — flat per-face geometric normals only\n\n")
            for x, y, z in self.verts:
                fp.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
            fp.write("\n")
            for face in self.faces:
                fp.write("f " + " ".join(str(i) for i in face) + "\n")
        print(f"  ✓ {path}  ({len(self.verts)} verts, {len(self.faces)} faces)")


# ─────────────────────────────────────────────────────────────────────────────
# Geometry primitives
# ─────────────────────────────────────────────────────────────────────────────

def _ring(b: ObjBuilder, cx, cy, cz, r, n_seg, y_offset=0.0):
    """Add `n_seg` verts on a circle in X-Z at height cy+y_offset. Return 1-based indices."""
    indices = []
    for i in range(n_seg):
        a = 2 * math.pi * i / n_seg
        idx = b.v(cx + r * math.cos(a), cy + y_offset, cz + r * math.sin(a))
        indices.append(idx)
    return indices


def _connect_rings(b: ObjBuilder, bot, top):
    """Connect two rings of equal length with quad faces (2 tris each)."""
    n = len(bot)
    for i in range(n):
        j = (i + 1) % n
        b.add_quad(bot[i], bot[j], top[j], top[i])


def _cap(b: ObjBuilder, ring_indices, center_idx, flip=False):
    """Fan-fill a ring to a center vertex. If flip, reverse winding."""
    n = len(ring_indices)
    for i in range(n):
        j = (i + 1) % n
        if flip:
            b.f(center_idx, ring_indices[j], ring_indices[i])
        else:
            b.f(center_idx, ring_indices[i], ring_indices[j])


def _cone_frustum(b: ObjBuilder, cx, cz, y_bot, y_top, r_bot, r_top, n_seg):
    """A tapered cylinder/frustum. Returns (bottom_ring, top_ring)."""
    bot = _ring(b, cx, y_bot, cz, r_bot, n_seg)
    top = _ring(b, cx, y_top, cz, r_top, n_seg)
    _connect_rings(b, bot, top)
    return bot, top


def _closed_frustum(b: ObjBuilder, cx, cz, y_bot, y_top, r_bot, r_top, n_seg):
    """Frustum with both caps filled."""
    bot, top = _cone_frustum(b, cx, cz, y_bot, y_top, r_bot, r_top, n_seg)
    bc = b.v(cx, y_bot, cz)
    _cap(b, bot, bc, flip=True)
    tc = b.v(cx, y_top, cz)
    _cap(b, top, tc, flip=False)


# ─────────────────────────────────────────────────────────────────────────────
# GROUND PLANE  — flat island base (a hex-ish platform with beveled edge)
# ─────────────────────────────────────────────────────────────────────────────

def make_ground():
    b = ObjBuilder()
    # Simple large quad ground plane at y=0, extending ±size in X and Z
    size = 12.0
    thickness = 0.4  # give it a visible side so outlines appear

    # Top face
    t1 = b.v(-size, 0, -size)
    t2 = b.v( size, 0, -size)
    t3 = b.v( size, 0,  size)
    t4 = b.v(-size, 0,  size)
    b.add_quad(t1, t2, t3, t4)

    # Bottom face
    b1 = b.v(-size, -thickness, -size)
    b2 = b.v( size, -thickness, -size)
    b3 = b.v( size, -thickness,  size)
    b4 = b.v(-size, -thickness,  size)
    b.add_quad(b4, b3, b2, b1)  # reversed winding

    # Four side walls
    b.add_quad(t1, t4, b4, b1)  # -X
    b.add_quad(t2, t1, b1, b2)  # -Z
    b.add_quad(t3, t2, b2, b3)  # +X
    b.add_quad(t4, t3, b3, b4)  # +Z

    b.write(os.path.join(OUT_DIR, "ground.obj"))


# ─────────────────────────────────────────────────────────────────────────────
# CHARACTER  — blocky humanoid: head cube, torso box, arms, legs
# ─────────────────────────────────────────────────────────────────────────────

def _box(b: ObjBuilder, cx, cy, cz, hx, hy, hz):
    """Axis-aligned box centred at (cx, cy, cz) with half-extents hx, hy, hz."""
    x0, x1 = cx - hx, cx + hx
    y0, y1 = cy - hy, cy + hy
    z0, z1 = cz - hz, cz + hz

    v = [
        b.v(x0, y0, z0), b.v(x1, y0, z0), b.v(x1, y0, z1), b.v(x0, y0, z1),  # bottom
        b.v(x0, y1, z0), b.v(x1, y1, z0), b.v(x1, y1, z1), b.v(x0, y1, z1),  # top
    ]
    # bottom
    b.add_quad(v[3], v[2], v[1], v[0])
    # top
    b.add_quad(v[4], v[5], v[6], v[7])
    # front (+Z)
    b.add_quad(v[7], v[6], v[2], v[3])
    # back (-Z)
    b.add_quad(v[5], v[4], v[0], v[1])
    # left (-X)
    b.add_quad(v[4], v[7], v[3], v[0])
    # right (+X)
    b.add_quad(v[6], v[5], v[1], v[2])


def make_character():
    b = ObjBuilder()

    # --- proportions (world-unit scale; character is ~2.4 units tall) ---
    # Feet at y=0 (standing on ground plane)

    # Legs — two short boxes
    leg_hx, leg_hy, leg_hz = 0.18, 0.45, 0.18
    leg_y = leg_hy  # center y
    _box(b, -0.22, leg_y, 0, leg_hx, leg_hy, leg_hz)   # left leg
    _box(b,  0.22, leg_y, 0, leg_hx, leg_hy, leg_hz)   # right leg

    # Torso — wider box
    torso_hx, torso_hy, torso_hz = 0.40, 0.50, 0.22
    torso_y = 2 * leg_hy + torso_hy
    _box(b, 0, torso_y, 0, torso_hx, torso_hy, torso_hz)

    # Arms — two thin boxes, angled slightly out
    arm_hx, arm_hy, arm_hz = 0.14, 0.42, 0.14
    arm_y = torso_y + 0.08  # slightly below shoulder
    _box(b, -(torso_hx + arm_hx + 0.04), arm_y, 0, arm_hx, arm_hy, arm_hz)  # left
    _box(b,  (torso_hx + arm_hx + 0.04), arm_y, 0, arm_hx, arm_hy, arm_hz)  # right

    # Head — cube, slightly larger than torso width
    head_h = 0.38
    head_y = 2 * leg_hy + 2 * torso_hy + head_h
    _box(b, 0, head_y, 0.02, head_h, head_h, head_h)

    b.write(os.path.join(OUT_DIR, "character.obj"))


# ─────────────────────────────────────────────────────────────────────────────
# TREES  — three stylised variants using frustum stacks
# ─────────────────────────────────────────────────────────────────────────────

def make_tree_a(cx=0.0, cz=0.0):
    """Tree A: conical / Christmas-tree style. Trunk + 3-tier cone foliage."""
    b = ObjBuilder()
    seg = 6  # hexagonal cross-section → chunky low-poly

    # Trunk
    _closed_frustum(b, cx, cz, y_bot=0.0, y_top=1.2, r_bot=0.18, r_top=0.14, n_seg=seg)

    # Three foliage cones (largest at bottom, smallest at top)
    _closed_frustum(b, cx, cz, y_bot=0.7, y_top=1.8, r_bot=1.1, r_top=0.05, n_seg=seg)
    _closed_frustum(b, cx, cz, y_bot=1.4, y_top=2.6, r_bot=0.85, r_top=0.05, n_seg=seg)
    _closed_frustum(b, cx, cz, y_bot=2.1, y_top=3.3, r_bot=0.62, r_top=0.05, n_seg=seg)

    b.write(os.path.join(OUT_DIR, "tree_a.obj"))


def make_tree_b(cx=0.0, cz=0.0):
    """Tree B: layered / tiered flat discs for a top-down garden look."""
    b = ObjBuilder()
    seg = 8  # octagonal

    # Trunk
    _closed_frustum(b, cx, cz, y_bot=0.0, y_top=1.5, r_bot=0.16, r_top=0.12, n_seg=seg)

    # 4 flat disc layers (short cylinders)
    for i, (yb, r) in enumerate([(1.2, 1.0), (1.6, 0.82), (2.0, 0.62), (2.4, 0.40)]):
        _closed_frustum(b, cx, cz, y_bot=yb, y_top=yb + 0.30, r_bot=r, r_top=r * 0.95, n_seg=seg)

    b.write(os.path.join(OUT_DIR, "tree_b.obj"))


def make_tree_c(cx=0.0, cz=0.0):
    """Tree C: round / bushy — sphere approximated by stacked ring frustums."""
    b = ObjBuilder()
    seg = 8

    # Trunk
    _closed_frustum(b, cx, cz, y_bot=0.0, y_top=1.0, r_bot=0.20, r_top=0.15, n_seg=seg)

    # Approximate sphere with 5 stacked frustums
    sphere_r = 1.1
    sphere_cy = 2.0
    n_slices = 5
    for s in range(n_slices):
        t0 = s / n_slices
        t1 = (s + 1) / n_slices
        a0 = math.pi * t0 - math.pi / 2  # from bottom to top
        a1 = math.pi * t1 - math.pi / 2
        y0 = sphere_cy + sphere_r * math.sin(a0)
        y1 = sphere_cy + sphere_r * math.sin(a1)
        r0 = sphere_r * math.cos(a0)
        r1 = sphere_r * math.cos(a1)
        _closed_frustum(b, cx, cz, y_bot=y0, y_top=y1, r_bot=max(r0, 0.01), r_top=max(r1, 0.01), n_seg=seg)

    b.write(os.path.join(OUT_DIR, "tree_c.obj"))


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("Generating Skypop Collective low-poly assets …\n")
    make_ground()
    make_character()
    make_tree_a()
    make_tree_b()
    make_tree_c()
    print("\nAll meshes written to:", OUT_DIR)
